language: python

python:
  - "3.7-dev"

branches:
  only:
    - master

notifications:
  recipients:
    - buriola@google.com
    - ramaro@google.com
    - ademaria@google.com
    - chifor@google.com
  email:
    on_success: change
    on_failure: always

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gnupg2

install:
  - pip3 install -r requirements.txt

script:
  - make test
