language: python

python:
  - "3.7-dev"

branches:
  only:
    - master

notifications:
  recipients:
    - buriola@google.com
    - ramaro@google.com
    - ademaria@google.com
    - chifor@google.com
  email:
    on_success: change
    on_failure: always

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y;
  - sudo apt-get -qq update
  - sudo apt-get install -y g++-4.9
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9
  - sudo apt-get install -y gnupg2

install:
  - pip3 install -r requirements.txt

script:
  - make test
