language: python
cache: pip
python:
  - "3.7-dev"
branches:
  only:
    - master
    - /v(\d+\.){2}\d+(-rc\.\d+)?/ # reged for tag branches e.g. v0.22.0-rc.1, v0.22.0 etc
notifications:
  recipients:
    - kapitan@google.com
  email:
    on_success: change
    on_failure: always
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y;
  - sudo apt-get -qq update
  - sudo apt-get install -y g++-4.9
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9
  - sudo apt-get install -y gnupg2
install:
  - pip3 install -r requirements.txt

script:
  - make test

after_success:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then bash ./scripts/inc_version.sh fi

before_deploy:
  - echo $TRAVIS_BRANCH

deploy:
  - provider: pypi
    distributions: sdist bdist_wheel
    skip_existing: true
    user:
      secure: REHK3fFiXqp56I1nWzBmhkRf9uuNDIOH4tBpxYb/H++Geyl8qGL3PTPdS5MQQMMAhhqXOughQY2KNApKODsiL4LNoNlqE+C9IFgWgt6nlzFV3yNSZPC4iHMe2ggLkA15YRoKcha4x+K70HQtsLOfH1LhvBGhJzG5M6D2pN1+aY4+8g4JADGtEj9Ey6gMJKj63Vl1Eqz5Gc5yHPwJAQJsTXdCHPA3Lvpc9u75+QMe+C04NvyC+TE5i7zp4Bc1rJ1eEfcY5CuhjN3K5UGVtFJ84xFR6SJ7Hur9ONm7Cpaesq7qr+BY9ejQqXm0gs8u+Uv0Lcc65n228QAkqML3N5xtJFPCICmHPu2CrntIAyOboHXgU6VHv79r68cteo/nQOob8vjFNu6jJxsmKJv/TBD2aMc+pF8+uWQxr+GkfENnoYQATQGh7CQ1ZPkGhbsdpDga+IPRmWDRdY5vFPDQspLB7+nIWY4v4WvtOmnlrQGDmhSuu8/71qyMKVLuDQrI9NSR56WKL/lxnZHJA06M83oI1JU7XRmf1PTWosB0Apg+Zdk7KObrcxyJfWQTnTO8ruvZoUsGIzZ3JTAnA5rHOgQE+kbPt+vy3SAmZ490Jj+MezByLOCnOR1y+8VwnwLogNxiwmRtuUBFXf7tOyWYduxERy8gWRILmkFAGCkppT4WrQ4=
    password:
      secure: GBENUUiSJWHqQNU6NnKrbWSDIoTTPsowV9oME3eTXFOcyvZLL5W0xs5TwOXZxPyz0eaQ20F+o9rT8jiuhe9laA3gDnID109wznuRwY1uGsWP2xolRwZIDeikBS/V7LSrvm69IDGbBuyakWOS0Z1GgPKW3NZzJRYnWhwRolxgqrXmCtK5yiPBHMWRlwn+KPpjGkDKufw47PKOomxScmSeXv3wRk85azWbriNFbtnbymqGut2VqccdbWrQPZ9VaKPbOolnOA6XC95ib4sMyXzpTpwVfsPeBSlYQoCNr6G4QQ3P8x93/twFwFSTGoGqqF5qa8xsvu7KyinjBZvzsTYdTq/2KTKhogSQRkxhcIR+bWBguGWyim1zptbHI0NYPhAEwOtwWT94lXPaisDyCIgCXmMm9f68ViJ4qpfD6o1qaQ+iSmHq16Q+p3CAstKTbUhIEKZomkVwPc7M9D2vUj+LphdGGn8Qp2rbz/jbkfJjVhNJRYrhJuCwtK7O2icf5fgLHruhFKBYeiNepAbF9wyleAREYGBoiw2PT2c0RUYyX+ITrNLsEcV7EzfT7qOm3Pl/ONQ9VV3IaXXWExpOvPdSl3toyAAPqYJ0Zsv23l4PIIY/g6VREyhtGQx2P8ZCGYVfVa+dd1FVH0hfXIsKnmsp0+Y1cpFb1pBa/XWlXRwjxZw=
    on:
      tags: true
after_deploy:
  - bash ./scripts/after_deploy.sh
