classes:
  - cluster.minikube
  - component.elasticsearch

parameters:
  kapitan:
    version: 1
    vars:
      target: minikube-es-2
      namespace: minikube-es-2
    compile:
      - output_path: manifests
        input_type: jsonnet
        input_paths:
          - targets/minikube-es/main.jsonnet
        output_type: yaml
      - output_path: scripts
        input_type: jinja2
        input_paths:
          - scripts
      - output_path: .
        input_type: jinja2
        input_paths:
          - targets/minikube-es/docs/README.md
  namespace: minikube-es

  elasticsearch:
    replicas: 2
